name: SonarCloud Scan

on:
  push:
    branches:
      - "master"
      - "lab_5_project_0.1.0"

jobs:
  sonarCloudTrigger:
    name: sonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Analize with SonarCloud
        uses sonarsource/sonarcloud-github-action@v1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
